FROM alpine:latest
#COPY .env .env
#RUN export $(cat .env | xargs) && echo "Hello from App2 with $API_URL"
#CMD ["sh", "-c", "export $(cat .env | xargs) && echo Hello from App2 with $API_URL"]

ARG API_URL='UNSUCCESSFUL'

RUN echo Hello from App2 with $API_URL